### ISSUE TITLE
Error message while pip installing (installation is still successful)

### ISSUE THREAD

**Issue by giadarol** [rdemaria/pytimber#71]
Here what I get:
```bash
pip install pytimber
Collecting pytimber
  Downloading https://files.pythonhosted.org/packages/f2/c9/cdaf9a6fcde370cacf0ea1ea9e6cee9415835f278efe0a661eeedf1fa44d/pytimber-2.7.0.tar.gz
Collecting JPype1>=0.6.2 (from pytimber)
  Downloading https://files.pythonhosted.org/packages/78/7d/3b8b60c7d430a07c19a1401f6e186e089a2d79222b31fc26d7dd07ffcba4/JPype1-0.7.1-cp37-cp37m-manylinux1_x86_64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 8.3MB/s 
Collecting cmmnbuild-dep-manager>=2.1.2 (from pytimber)
  Downloading https://files.pythonhosted.org/packages/39/9a/4a5049a716626b5ded4a6733c6f88470547d7ed5cd5d05a82d20cb3104a9/cmmnbuild-dep-manager-2.3.1.tar.gz
Requirement already satisfied: requests in /home/giadarol/miniconda3/lib/python3.7/site-packages (from cmmnbuild-dep-manager>=2.1.2->pytimber) (2.21.0)
Requirement already satisfied: six in /home/giadarol/miniconda3/lib/python3.7/site-packages (from cmmnbuild-dep-manager>=2.1.2->pytimber) (1.12.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/giadarol/miniconda3/lib/python3.7/site-packages (from requests->cmmnbuild-dep-manager>=2.1.2->pytimber) (3.0.4)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /home/giadarol/miniconda3/lib/python3.7/site-packages (from requests->cmmnbuild-dep-manager>=2.1.2->pytimber) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/giadarol/miniconda3/lib/python3.7/site-packages (from requests->cmmnbuild-dep-manager>=2.1.2->pytimber) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in /home/giadarol/miniconda3/lib/python3.7/site-packages (from requests->cmmnbuild-dep-manager>=2.1.2->pytimber) (2.8)
Building wheels for collected packages: pytimber, cmmnbuild-dep-manager
  Building wheel for pytimber (setup.py) ... error
  Complete output from command /home/giadarol/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-eg1d_nlf/pytimber/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-jx020g8n --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/pytimber
  copying pytimber/pytimber.py -> build/lib/pytimber
  copying pytimber/LHCBWS.py -> build/lib/pytimber
  copying pytimber/localdate.py -> build/lib/pytimber
  copying pytimber/__init__.py -> build/lib/pytimber
  copying pytimber/dataquery.py -> build/lib/pytimber
  copying pytimber/timberdata.py -> build/lib/pytimber
  copying pytimber/toolbox.py -> build/lib/pytimber
  copying pytimber/pagestore.py -> build/lib/pytimber
  copying pytimber/page.py -> build/lib/pytimber
  copying pytimber/LHCBSRT.py -> build/lib/pytimber
  installing to build/bdist.linux-x86_64/wheel
  running install
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-eg1d_nlf/pytimber/setup.py", line 62, in <module>
      'install': install
    File "/home/giadarol/miniconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/giadarol/miniconda3/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/giadarol/miniconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/giadarol/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/giadarol/miniconda3/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "/home/giadarol/miniconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/giadarol/miniconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-eg1d_nlf/pytimber/setup.py", line 42, in run
      import cmmnbuild_dep_manager
  ModuleNotFoundError: No module named 'cmmnbuild_dep_manager'
  
  ----------------------------------------
  Failed building wheel for pytimber
  Running setup.py clean for pytimber
  Building wheel for cmmnbuild-dep-manager (setup.py) ... done
  Stored in directory: /home/giadarol/.cache/pip/wheels/92/16/dd/265f0527b41ce078881d4ef1306b77a95a575fab52db0ca3f3
Successfully built cmmnbuild-dep-manager
Failed to build pytimber
Installing collected packages: JPype1, cmmnbuild-dep-manager, pytimber
  Running setup.py install for pytimber ... -

done
Successfully installed JPype1-0.7.1 cmmnbuild-dep-manager-2.3.1 pytimber-2.7.0
```

**Comment by pelson** [comment]
This will have been fixed when we added a ``pyproject.toml`` file to PyTimber (assuming you have ``pip>=18``).
